import Footer from '@/components/Footer'
import NavBar from '@/components/NavBar'
import React, { useState } from 'react'
import styles from '../../styles/login.module.css'
import Image from 'next/image'
import Head from 'next/head'
const Index = () => {
   
    const [email, setEmail] = useState("");
    const [password, setPassword] = useState("");
    const [check, setCheck] = useState(null)
    const handleSubmitForm = (e) => {
        e.preventDefault();
    }
    return (
        <>
         <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
        <NavBar/>
        <div className={styles.LoginContainer}>
                <div className={styles.ImageContainer}>
                    <Image src="/signup.jpg" alt='signupImage' fill />
                </div>
                <div className={styles.formContainer}>
                    <h1>Login</h1>
                    <form action="">
                        <input type="email" required name="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder='Email' />
                        <input type="password" required name='password' value={password} onChange={(e) => setPassword(e.target.value)} placeholder='Password' />
                        <div className={styles.checkboxContainer}>
                            <input value="checkbox" onChange={(e) => setCheck(e.target.checked)} type="checkbox" /> <span>Remember Me</span>
                        </div>
                        <button onSubmit={handleSubmitForm}>LOGIN</button>
                    </form>
                </div>
            </div>
            <Footer/>
        </>
    )
}

export default Index