import React from 'react';
import { useRouter } from 'next/router';
import styles from '../../styles/singleblog.module.css';
import NavBar from '@/components/NavBar';
import Footer from '@/components/Footer';
import Image from 'next/image';
import Head from 'next/head';

const SingleBlog = () => {
  const router = useRouter();
  const { blog } = router.query;
  const blogId = parseInt(blog, 10); // Convert to number

  const dummyData = [
    {
      currentPageIndex: 1,
      coverImage: "/blogone.png",
      author: "zendora",
      date: "December 21, 2022",
      title: "The 8 Best Clay Masks For Acne Prone Skin",
      description: "There are many variations of passages of Lorem Ipsum available, but the majority have",
      relatedCat: "spa",
    },
    {
      currentPageIndex: 2,
      coverImage: "/blogtwo.png",
      author: "zendora",
      date: "December 21, 2022",
      title: "Well-ageing: Why is the skin matrisome important?",
      description: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece",
      relatedCat: "spa",
    }
  ];

  // Find the data of the current page
  const currentPageData = dummyData.find(item => item.currentPageIndex === blogId);

  // Check if currentPageData is available
  if (!currentPageData) {
    return <div>Page not found</div>;
  }

  const handleTagClick = (category) => {
    router.push(`/Blogs/${category}`);
  };

  return (
    <>
     <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <NavBar />
      <div className={styles.blogContainer}>
        <div className={styles.postcontainer}>
          <div className={styles.imageContainer}>
            {currentPageData.coverImage && (
              <Image src={currentPageData.coverImage} alt='salonImage' fill />
            )}
          </div>
          <h1>{currentPageData?.title}</h1>
          <p className={styles.myDate}>Date: {currentPageData?.date}</p>
          <p className={styles.mydesc}>{currentPageData?.description}</p>
        </div>
        <div className={styles.relatedTagContainer}>
          {dummyData.map(item => (
            <div
              className={styles.imageContent}
              key={item?.currentPageIndex}
              onClick={() => handleTagClick(item?.currentPageIndex)}
            >
              <div className={styles.relatedImageContainer}>
                {item.coverImage && (
                  <Image src={item?.coverImage} alt='salonImage' fill />
                )}
              </div>
              <div className={styles.relateUpper}>
                <h3>{item?.title}</h3>
              </div>
              <div className={styles.relateBottom}>
                <p>There are many variations of passages of Lorem Ipsum available, but the majority have</p>
              </div>
            </div>
          ))}
        </div>
      </div>
      <Footer />
    </>
  );
};

export default SingleBlog;
